name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Bun
        uses: oven-sh/setup-bun@22457c87c1b161cf7dde222c3e82b2b5f8d2bed2

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test
        env:
          SOCKET_CLI_API_TOKEN: ${{ secrets.SOCKET_CLI_API_TOKEN }}

      - name: Test blocking on install
        shell: bash
        run: |
          if bun add lodahs; then
            echo "ERROR: Scanner failed to block malicious package"
            exit 1
          else
            echo "SUCCESS: Scanner blocked malicious package as expected"
            exit 0
          fi
