name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest

    needs: test

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Bun
        uses: oven-sh/setup-bun@22457c87c1b161cf7dde222c3e82b2b5f8d2bed2

      - name: Update npm to latest just to get --provenance
        run: bun install -g npm@latest

      - name: Install dependencies
        run: bun install

      - name: Publish to NPM
        run: npm publish --provenance
